kotlinMuiVersion=5.15.8-pre.630
kotlinMuiIconsVersion=5.15.8-pre.630
kotlinReactVersion=18.2.0-pre.630
kotlinReactDomVersion=18.2.0-pre.630
csstypeVersion=2.0.0-pre.630
kotlinxSerializationVersion=1.6.0
kotlinxCoroutinesVersion=1.7.3
muiNpmVersion=5.15.8
muiIconsNpmVersion=5.15.8
emotionReactNpmVersion=11.11.1
emotionStyledNpmVersion=11.11.0
reactNpmVersion=18.2.0
reactDomNpmVersion=18.2.0
